[Gnome_themes_extra]
git-tree-sha1 = "98057e5b255ea1ff09ebb35cec6fc6b1e053b802"

    [[Gnome_themes_extra.download]]
    sha256 = "d111eaa9114a22201e0835f3cd1aaeab488ba4268aacc768a982ece02f272c32"
    url = "https://github.com/JuliaBinaryWrappers/Gnome_themes_extra_jll.jl/releases/download/Gnome_themes_extra-v3.28.0+2/Gnome_themes_extra.v3.28.0.any.tar.gz"
