# Autogenerated wrapper script for Gnome_themes_extra_jll for any
export adwaita_index

using GTK3_jll
using Librsvg_jll
JLLWrappers.@generate_wrapper_header("Gnome_themes_extra")
JLLWrappers.@declare_file_product(adwaita_index)
function __init__()
    JLLWrappers.@generate_init_header(GTK3_jll, Librsvg_jll)
    JLLWrappers.@init_file_product(
        adwaita_index,
        "share/themes/Adwaita/index.theme",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
